_wandb:
    value:
        cli_version: 0.25.0
        e:
            ko1ypuwkm8g8t0uk5ywluhrkcbskwu55:
                args:
                    - --end_inner_fraction=0
                    - --end_weight=1
                    - --epochs=1000
                    - --hidden_dim=256
                    - --suite=mt10
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1021821579264"
                        used: "175631249408"
                email: nancy.x.bao@gmail.com
                executable: C:\Users\nancy\miniconda3\python.exe
                git:
                    commit: d7a542d6a2bd87b1eccaa3d05afb444a7c371e90
                    remote: git@github.com:alee51/CS229_FinalProject.git
                host: NB_Thinkpad_X9
                memory:
                    total: "33847832576"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\nancy\Desktop\CS229_FinalProject\run_sweep.py
                python: CPython 3.13.11
                root: C:\Users\nancy\Desktop\CS229_FinalProject
                startedAt: "2026-02-17T20:19:54.528473Z"
                writerId: ko1ypuwkm8g8t0uk5ywluhrkcbskwu55
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.13.11
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
end_inner_fraction:
    value: 0
end_weight:
    value: 1
epochs:
    value: 1000
hidden_dim:
    value: 256
suite:
    value: mt10
