_wandb:
    value:
        cli_version: 0.25.0
        e:
            d64iaxvotj1pd3at6ixurmp9lvhiov6h:
                args:
                    - --end_inner_fraction=0
                    - --end_weight=1
                    - --epochs=500
                    - --hidden_dim=256
                    - --suite=mt10
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1021821579264"
                        used: "174196088832"
                email: nancy.x.bao@gmail.com
                executable: C:\Users\nancy\miniconda3\python.exe
                git:
                    commit: d7a542d6a2bd87b1eccaa3d05afb444a7c371e90
                    remote: git@github.com:alee51/CS229_FinalProject.git
                host: NB_Thinkpad_X9
                memory:
                    total: "33847832576"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\nancy\Desktop\CS229_FinalProject\run_sweep.py
                python: CPython 3.13.11
                root: C:\Users\nancy\Desktop\CS229_FinalProject
                startedAt: "2026-02-17T12:26:49.478431Z"
                writerId: d64iaxvotj1pd3at6ixurmp9lvhiov6h
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 15
            "4": 3.13.11
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
approach:
    value: baseline
batch_size:
    value: 64
clip_actions:
    value: true
end_fraction:
    value: 0.3
end_inner_fraction:
    value: 0
end_inner_weight:
    value: null
end_upsample:
    value: false
end_weight:
    value: 1
episodes:
    value: 500
epochs:
    value: 500
hidden_dim:
    value: 256
hidden_sizes:
    value:
        - 256
        - 256
lr:
    value: 0.0003
lr_decay_epoch:
    value: 250
lr_decay_gamma:
    value: 0.5
model:
    value: run_20260217_042108_end1_clip_mt10.pth
save_name:
    value: cloned_policy.pth
seed:
    value: 42
source:
    value: auto
suite:
    value: mt10
task_or_suite:
    value: mt10
training_run_id:
    value: pamkuyhm
